
CREATE SCHEMA "VNETCON";

CREATE TABLE "VNETCON"."REST_SERVLET_CONFIG" (
	"REST_ENDPOINT_ID" varchar(100) NOT NULL,
	"REST_ENDPOINT" varchar(100) NOT NULL,
	"VERSION" varchar(100) NOT NULL,
	"ALLOWED_TOKENS" varchar(2000) DEFAULT 'ALL'::character varying,
	"ALLOWED_IPADDRESSES" varchar(2000) DEFAULT 'ALL'::character varying,
	"ENABLED" int4 DEFAULT 1,
	CONSTRAINT "REST_SERVLET_CONFIG_pkey" PRIMARY KEY ("REST_ENDPOINT_ID")
);

CREATE TABLE "VNETCON"."REST_SERVLET_FILE" (
	"FILEID" varchar(100) NOT NULL,
	"FILENAME" varchar(100) NOT NULL,
	"CONTENTTYPE" varchar(100) NOT NULL,
	"LENGTH" int4 NOT NULL,
	"CONTENT" bytea NOT NULL,
	"LOADTIME" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT rest_servlet_file_pk PRIMARY KEY ("FILEID")
);

CREATE TABLE "VNETCON"."REST_SERVLET_LOG" (
	"LOGTIME" timestamp,
	"SQL" text,
	"REQUEST_PARAMS" text,
	"RESPONSE_JSON" text,
	"REAL_VALUES" text,
	"MESSAGE" text
);

CREATE TABLE "VNETCON"."REST_SERVLET_SQL" (
	"REST_SQL_ID" varchar(100) NOT NULL,
	"REST_ENDPOINT" varchar(100) NOT NULL,
	"SQLTYPE" varchar(100) DEFAULT 'SELECT'::character varying NOT NULL,
	"ORDERNUM" int4 NOT NULL,
	"JSON_SQL" varchar(2000) NOT NULL,
	CONSTRAINT "REST_SERVLET_SQL_pkey" PRIMARY KEY ("REST_SQL_ID")
);